### ISSUE TITLE
Unable to control playback from EMUI 12 Control Panel

### ISSUE THREAD

**Issue by metalichesky** [HMS-Core/hms-audio-demo#1]
Hello!
This demo application is almost fully functional on my Huawei nova Y70 device and plays audio. 
However, I encountered the following problem: the demo app displays the playback status notification in the notification panel, but does not display the playback status in the Control Panel, which was introduced in EMUI 12.

I cloned the repository locally, opened the project in Android Studio. Next, I created a developer account on developer.huawei.com, passed verification and created a new application in the dashboard. Then I imported agconnect-services.json into the project according to the instructions. My demo application has application id com.metalichesky.audiokitdemo.
However, this also did not help to display the playback status in the Control Panel of EMUI 12. What steps should I take to ensure that my own application based on this demo application can be displayed in the Control Panel to control playback? 
![control_panel](https://github.com/HMS-Core/hms-audio-demo/assets/25653164/ff39e5bc-faa5-4244-91d0-ae7f890c6f84)

**Comment by peura-toni** [comment]
Hi,

After consulting HUAWEI Developers, "This function needs to be implemented through the MediaSession of Android. After the function is implemented, you need to apply for adding the trustlist. Currently, this function is available only for top apps. This function needs to be adapted and applied for the trustlist separately. The adaptation and application for the trustlist outside China have been organized in a unified manner before, but there is no plan at present."

That's what was said about it. I hope it answered your question.

**Comment by metalichesky** [comment]
Yes, thanks! I received the information I needed. It turns out that independent developers are not able to make full support of their applications for many new Huawei smartphones at the moment if they are not from China, and this is sad. Huawei is a good platform, I hope in the future the capabilities of developers for this platform will only increase.

**Comment by metalichesky** [comment]
Hello! For those who need it: Huawei no longer adds apps to the trustlist and therefore there is no chance of your app being supported in the Control Panel in EMUI 12 and later. I received the following response from Huawei Developers support:

![image](https://github.com/HMS-Core/hms-audio-demo/assets/25653164/ac552bc2-d852-4f33-aec2-7ba27aafa3ae)
